---
- name: Barman | Test for existing config
  stat:
    path: '{{barman_configuration_file_path}}'
  register: barman_config_file_stat

- name: Barman | Backup existing config
  command: 'mv {{barman_configuration_file_path}} {{barman_configuration_file_path}}.ansible_bak'
  when: barman_config_file_stat.stat.exists == True

- name: Barman | update config
  template:
    src: ../templates/barman.conf.j2
    dest: '{{barman_configuration_file_path}}'
    owner: '{{barman_user}}'
    group: '{{barman_group}}'
    mode: 0644
    
